# Generated by Django 5.2.17 on 2026-08-16 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storybooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('name', models.CharField(max_length=100, verbose_name='제품명')),
                ('line', models.CharField(blank=True, max_length=50, verbose_name='라인')),
                ('pattern', models.CharField(blank=True, max_length=50, verbose_name='패턴')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='색상')),
                ('product_code', models.CharField(max_length=50, unique=True, verbose_name='제품 코드')),
                ('capacity', models.PositiveIntegerField(default=20, help_text='이 제품에 담을 수 있는 추억구슬 개수', verbose_name='추억구슬 용량')),
                ('warranty_months', models.PositiveIntegerField(default=24, verbose_name='보증 기간(개월)')),
                ('care_guide', models.TextField(blank=True, verbose_name='보관법')),
                ('image_url', models.URLField(blank=True, verbose_name='이미지 URL')),
                ('storybook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='storybooks.storybook', verbose_name='연관 스토리북')),
            ],
            options={
                'verbose_name': '제품(마스터)',
                'verbose_name_plural': '제품(마스터)',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('serial_no', models.CharField(max_length=64, unique=True, verbose_name='시리얼 번호')),
                ('acquired_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 시각')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='소유자')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_by', to='products.product', verbose_name='제품')),
            ],
            options={
                'verbose_name': '보유 제품',
                'verbose_name_plural': '보유 제품',
                'db_table': 'user_products',
                'ordering': ['-acquired_at'],
            },
        ),
    ]
