# Generated by Django 5.2.17 on 2026-08-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='capacity',
            field=models.PositiveIntegerField(default=20, help_text='이 제품에 담을 수 있는 추억 개수', verbose_name='추억 용량'),
        ),
    ]
