# Generated by Django 5.2.17 on 2026-08-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store_url',
            field=models.URLField(blank=True, verbose_name='스토어 링크'),
        ),
    ]
