# Generated by Django 5.2.17 on 2026-08-16 04:24

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('nickname', models.CharField(max_length=30, verbose_name='닉네임')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='생년월일')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('agree_data', models.BooleanField(default=False, verbose_name='개인정보 수집·이용 동의')),
                ('agree_marketing', models.BooleanField(default=False, verbose_name='마케팅 수신 동의')),
                ('notify_memory', models.BooleanField(default=True, verbose_name='근처 추억구슬 알림')),
                ('notify_place', models.BooleanField(default=True, verbose_name='특별 장소 알림')),
                ('notify_ad', models.BooleanField(default=False, verbose_name='광고성 알림')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('is_staff', models.BooleanField(default=False, verbose_name='관리자 페이지 접근')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저',
                'db_table': 'users',
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
