# Generated by Django 5.2.17 on 2026-08-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notify_memory',
            field=models.BooleanField(default=True, verbose_name='근처 추억 알림'),
        ),
    ]
