# Generated by Django 5.2.17 on 2026-08-17 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('doll', models.CharField(choices=[('bearbrick', '베어브릭'), ('rabbit', '토끼'), ('puppy', '퍼피'), ('dachshund', '닥스훈트')], max_length=20, verbose_name='인형')),
                ('pattern', models.CharField(choices=[('visetos', '비세토스'), ('lauretos', '로레토스'), ('cubic_monogram', '큐빅 모노그램')], max_length=20, verbose_name='패턴')),
                ('color', models.CharField(choices=[('cognac', '꼬냑'), ('black', '블랙'), ('white', '화이트'), ('silver', '실버'), ('pink', '핑크')], max_length=20, verbose_name='색상')),
                ('equipped_product', models.ForeignKey(blank=True, help_text='홈 화면 상단 용량 게이지는 이 제품 하나의 값을 쓴다.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_by', to='products.userproduct', verbose_name='장착 제품')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='character', to=settings.AUTH_USER_MODEL, verbose_name='소유자')),
            ],
            options={
                'verbose_name': '캐릭터',
                'verbose_name_plural': '캐릭터',
                'db_table': 'characters',
            },
        ),
    ]
