# Generated by Django 5.2.17 on 2026-08-16 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('storybooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('type', models.CharField(choices=[('city', '도시'), ('store', '매장')], max_length=10, verbose_name='종류')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='주소')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='위도')),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='경도')),
                ('radius', models.PositiveIntegerField(default=200, verbose_name='인식 반경(m)')),
                ('storybook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='storybooks.storybook', verbose_name='해금될 스토리북')),
            ],
            options={
                'verbose_name': '특별 장소',
                'verbose_name_plural': '특별 장소',
                'db_table': 'places',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('photo', models.CharField(blank=True, help_text='POST /upload 가 돌려준 key', max_length=255, verbose_name='사진 키')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='위도')),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='경도')),
                ('place_name', models.CharField(blank=True, max_length=100, verbose_name='장소명')),
                ('note', models.TextField(blank=True, verbose_name='한 줄 기록')),
                ('visibility', models.CharField(choices=[('public', '공개'), ('private', '비공개')], default='public', max_length=10, verbose_name='공개 설정')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('user_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='products.userproduct', verbose_name='담은 제품')),
            ],
            options={
                'verbose_name': '추억구슬',
                'verbose_name_plural': '추억구슬',
                'db_table': 'memories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lat', 'lng'], name='idx_memory_latlng'), models.Index(fields=['owner', '-created_at'], name='idx_memory_owner_created')],
            },
        ),
    ]
