# Generated by Django 5.2.17 on 2026-08-17 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'ordering': ['-created_at'], 'verbose_name': '추억', 'verbose_name_plural': '추억'},
        ),
    ]
