# Generated by Django 5.2.17 on 2026-08-16 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Storybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('scope', models.CharField(choices=[('product', '제품'), ('place', '특별 장소')], max_length=10, verbose_name='종류')),
                ('title', models.CharField(max_length=120, verbose_name='제목')),
                ('cover_url', models.URLField(blank=True, verbose_name='표지 이미지 URL')),
            ],
            options={
                'verbose_name': '스토리북',
                'verbose_name_plural': '스토리북',
                'db_table': 'storybooks',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('chapter_no', models.PositiveIntegerField(verbose_name='챕터 번호')),
                ('title', models.CharField(max_length=120, verbose_name='제목')),
                ('body', models.TextField(blank=True, verbose_name='본문')),
                ('required_memories', models.PositiveIntegerField(default=0, help_text='이 개수 이상 추억을 담으면 열린다.', verbose_name='해금 필요 추억 수')),
                ('storybook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='storybooks.storybook', verbose_name='스토리북')),
            ],
            options={
                'verbose_name': '챕터',
                'verbose_name_plural': '챕터',
                'db_table': 'chapters',
                'ordering': ['storybook_id', 'chapter_no'],
            },
        ),
        migrations.CreateModel(
            name='Unlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='해금 시각')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='storybooks.chapter', verbose_name='챕터')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '해금 이력',
                'verbose_name_plural': '해금 이력',
                'db_table': 'unlocks',
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('storybook', 'chapter_no'), name='uniq_chapter_no_per_storybook'),
        ),
        migrations.AddConstraint(
            model_name='unlock',
            constraint=models.UniqueConstraint(fields=('user', 'chapter'), name='uniq_unlock_per_user_chapter'),
        ),
    ]
