# Generated by Django 5.2.17 on 2026-08-19 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storybooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('body', models.TextField(verbose_name='본문')),
                ('storybook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_stories', to='storybooks.storybook', verbose_name='스토리북')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_stories', to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
            options={
                'verbose_name': '생성 스토리',
                'verbose_name_plural': '생성 스토리',
                'db_table': 'generated_stories',
                'constraints': [models.UniqueConstraint(fields=('user', 'storybook'), name='uniq_generated_story_per_user_storybook')],
            },
        ),
    ]
